name: Clojurescript Track Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Running the Tests...
        uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :test
