name: Clojurescript Track Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Running the Tests...
        uses: actions/tools.deps-builder@v1.0.1
        with:
          tools-deps: 1.10.1.469
